name: Project auto-testing
on:
  push:
    branches:
      - main

permissions: {}

jobs:
  LinuxProjectTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Linux Project test
        run: | 
          curl -o test/test.sh -L https://raw.githubusercontent.com/alonitac/INTLinuxProject/main/test/test.sh
          bash test/test.sh